export default [
    { value: 1, name: "Homicide" },
    { value: 8, name: "Assault" },
    { value: 14, name: "Robbery" },
    { value: 17, name: "Other Offences Against the Person" },
    { value: 21, name: "Unlawful Entry" },
    { value: 27, name: "Arson" },
    { value: 28, name: "Other Property Damage" },
    { value: 29, name: "Unlawful Use of Motor Vehicle" },
    { value: 30, name: "Other Theft" },
    { value: 35, name: "Fraud" },
    { value: 39, name: "Handling Stolen Goods" },
    { value: 45, name: "Drug Offence" },
    { value: 47, name: "Liquor (excl. Drunkenness)" },
    { value: 51, name: "Weapons Act Offences" },
    { value: 52, name: "Good Order Offence" },
    { value: 54, name: "Traffic and Related Offences" },
    { value: 55, name: "Other" },
];